name: Deploy to minikube and test

on:
  push:
    branches: [ "master" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build and deploy to minikube
    steps:
    - uses: actions/checkout@v4
      with:
        repository: predanerd/kube-petclinic
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
    - name: Create namespaces
      run: |
        kubectl create ns pet-clinic-app
        kubectl create ns pet-clinic-db
    - name: Secret for SQL database
      run: |
        kubectl apply -f kube-deploy/03-java-app-deployment/secret.yml
        kubectl get secret -n pet-clinic-app
        kubectl get secret -n pet-clinic-db
    - name: Create and deploy SQL
      run : |
        kubectl apply -f kube-deploy/03-java-app-deployment/mysql/configmap.yml
        kubectl get cm -n pet-clinic-db
        kubectl apply -f kube-deploy/03-java-app-deployment/mysql/mysql.yml
        kubectl wait --for=condition=Ready pod/mysql-0 -n pet-clinic-db
        kubectl get sts -n pet-clinic-db
    - name: Deploy Java app
      run : |
        kubectl apply -f kube-deploy/03-java-app-deployment/java-app/configmap.yml
        kubectl get cm -n pet-clinic-app
        kubectl apply -f kube-deploy/03-java-app-deployment/java-app/java.yml
        kubectl wait --for=condition=Ready pod/java-app -n pet-clinic-app
        kubectl get deploy -n pet-clinic-app
    - name: Test service URLs
      run: |
        minikube service list
        minikube service java-app-service --url   
        echo "------------------opening the service------------------"
        curl $(minikube service java-app-service -n pet-clinic-app --url)
